### ISSUE TITLE
contact getting issue   setFormattedContactNumber(ContactNumberUtils.getPhoneNumber(getContactNumber(), countryCode));

### ISSUE THREAD

**Issue by nkrajadeveloper** [AppLozic/Applozic-Chat-SDK-Documentation#14]
setFormattedContactNumber(**ContactNumberUtils**.getPhoneNumber(getContactNumber(),*\* countryCode));

error in ContactNumberUtils  
and problem in gatting contact list in android platform 
plzz solve this issue

**Comment by Sunilkumarr** [comment]
@nkrajadeveloper  Hello ContactNumberUtils.java class is removed from Applozic android SDK .Are you accessing that class?
