### ISSUE TITLE
REST rest/ws/user/update is not working

### ISSUE THREAD

**Issue by jlubeck** [AppLozic/Applozic-Chat-SDK-Documentation#17]
I tried getting user details and that works fine, so my authentication tokens are correct, but when I try to use that endpoint with the following example JSON:

```
{ 
"displayName" : "Jan2",
"ofUserId" : "10154746478973369"
}
```

I´m getting this error:
```
{
  "status": "error",
  "errorResponse": [
    {
      "errorCode": "AL-AE-01",
      "description": "empty or null parameter",
      "displayMessage": "Unable to process"
    }
  ],
  "generatedAt": 1496277380642
}
```

Thank you

**Comment by priyadarshi** [comment]
@jlubeck 
remove ofUserId from json body and use ofUserId in request url parameter.

**Comment by jlubeck** [comment]
That worked! 
The docs don't specify that, maybe they should be more clear?
Thanks! Closing
